name = "skynote-ai-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.dev]
name = "skynote-ai-worker-dev"
vars = { ENVIRONMENT = "development" }

# D1 Database
[[env.dev.d1_databases]]
binding = "DB"
database_name = "cloudnotes-db-dev"
database_id = "placeholder-database-id"

# R2 Storage
[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "cloudnotes-dev-storage"

# Queues
[[env.dev.queues.producers]]
queue = "note-processing-dev"
binding = "NOTE_QUEUE"

[[env.dev.queues.consumers]]
queue = "note-processing-dev"
max_batch_size = 10
max_batch_timeout = 30

# AI bindings
[env.dev.ai]
binding = "AI"

[env.production]
name = "skynote-ai-worker-prod"
vars = { ENVIRONMENT = "production" }

# D1 Database
[[env.production.d1_databases]]
binding = "DB"
database_name = "cloudnotes-db-prod"
database_id = "placeholder-database-id"

# R2 Storage
[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "cloudnotes-prod-storage"

# Queues
[[env.production.queues.producers]]
queue = "note-processing-prod"
binding = "NOTE_QUEUE"

[[env.production.queues.consumers]]
queue = "note-processing-prod"
max_batch_size = 10
max_batch_timeout = 30

# AI bindings
[env.production.ai]
binding = "AI"